services:
  - type: web
    name: awg-portal
    runtime: node
    plan: free
    buildCommand: npm run render-build
    startCommand: NODE_ENV=production node dist/index.cjs
    envVars:
      - key: NODE_VERSION
        value: 20
